defaults:
  - /validation/data_loader_val_base@_here_
  - /logger_base@_here_
  - _self_

name: ${dataset.dataset_name}_${dataset.val.seq}
val_batch_freq: 1500
data_loader:
  gpu: 0
  args:
    batch_size: 1
    pin_memory: false
    shuffle: false
    num_workers: 0
    prefetch_factor: null


logger:
  saved_tensors:
    final_prediction:
    flow_gt_event_volume_new:

dataset:
  dataset_name: ${oc.select:dataset.dataset_name}
  representation_type: ${oc.select:dataset.representation_type}
  num_voxel_bins: ${oc.select:dataset.num_voxel_bins}
  dt: ${oc.select:dataset.dt}
  add_eigenvalues: ${oc.select:dataset.add_eigenvalues}
  add_filter_values: ${oc.select:dataset.add_filter_values}
  normalize_aux_voxel: ${oc.select:dataset.normalize_aux_voxel,true}
  tau: ${oc.select:dataset.tau}
  filter_size: ${oc.select:dataset.filter_size}
  in_memory: ${oc.select:dataset.in_memory}
  force_preprocess: ${oc.select:dataset.force_preprocess}
  do_not_save_preprocessed: ${oc.select:dataset.do_not_save_preprocessed}
  common:
    data_root: ${oc.select:dataset.common.data_root}
    test_root: ${oc.select:dataset.common.test_root}
    preprocessed_root: ${oc.select:dataset.common.preprocessed_root}
  train:
    seq: ${oc.select:dataset.train.seq}
  val:
    seq: ${oc.select:dataset.val.seq}
    recurrent: false


postprocess:

metrics:
  final_prediction_nonseq: ["L1", "L2", "1PE", "3PE"]
    
hydra:
  output_subdir: null
  
