[project]
name = "idnet"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "hdf5plugin>=6.0.0",
    "hydra-core>=1.3.2",
    "imageio>=2.37.0",
    "ipykernel>=7.1.0",
    "ipython>=9.6.0",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.7",
    "mkl>=2025.3.0",
    "omegaconf>=2.3.0",
    "opencv-python-headless>=4.11.0.86",
    "pandas>=2.3.3",
    "pathlib>=1.0.1",
    "tonic>=1.6.0",
    "torch<=2.7.1,>=2.2.0",
    "torch-geometric>=2.7.0",
    "torchinfo>=1.8.0",
    "torchvision<=0.24.0",
    "wandb>=0.22.3",
]
