deterministic: false
track: false
num_epoch: 100
data_loader:
  common:
    num_voxel_bins: 15
  train:
    gpu: 0
    args:
      batch_size: 3
  val:
    gpu: 0
    batch_freq: 1500
loss:
  final_prediction_nonseq:
    loss_type: sparse_l1
    weight: 1.0
    seq_weight: avg
    seq_norm: false

optim:
  optimizer: adam
  scheduler: onecycle
  lr: 1e-4

callbacks:
  logger:
    enable:
    log_keys:
      batch_end:
        - loss
        - lr


  validator:
    enable:
    frequency_type: step
    frequency: 500
    sanity_run_step: 3


validation:
  nonrec:
    dataset:
      common:
        data_root: ${dataset.common.data_root}
        test_root: ${dataset.common.test_root}
      representation_type: ${dataset.representation_type}
      train:
        use_all_seqs: false
        seq: [
            zurich_city_02_d,
            zurich_city_11_a,
            zurich_city_08_a,
            zurich_city_05_b
          ]
        add_eigenvalues: ${dataset.train.add_eigenvalues}
        tau: ${dataset.train.tau}
        filter_size: ${dataset.train.filter_size}
        in_memory: ${dataset.train.in_memory}
        force_preprocess: ${dataset.train.force_preprocess}
        do_not_save_preprocessed: ${dataset.train.do_not_save_preprocessed}
      val:
        add_eigenvalues: ${dataset.train.add_eigenvalues}
        tau: ${dataset.train.tau}
        filter_size: ${dataset.train.filter_size}
        in_memory: ${dataset.train.in_memory}
        force_preprocess: ${dataset.train.force_preprocess}      
        do_not_save_preprocessed: ${dataset.train.do_not_save_preprocessed}

model:
  pretrain_ckpt: null
  add_eigenvalues: ${dataset.train.add_eigenvalues}
  num_voxel_bins: ${data_loader.common.num_voxel_bins}

dataset:
  representation_type: voxel
  common:
    data_root: data/
    test_root: data/test/
  train:
    add_eigenvalues: false
    tau: 15000 
    filter_size: 7
    in_memory: true
    force_preprocess: true
    do_not_save_preprocessed: true

torch:
  debug_grad: false
  deterministic: false

wandb:
  enabled: true
  project: "idnet"
  run_name: "subdataset-model-change-id-8x-from-memory-force-preprocess"

defaults:
  - validation@_group_.nonrec: nonrec
  - hydra: custom_hydra
  - data_loader_base
  - torch_environ_base
  - model: id-8x # id-4x
  - dataset: dsec_augmentation
  - _self_
